version: "3.9"

networks:
    carwashnetwork:
        name: carwashnetwork

services:
    carwashdb:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: carwashdb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        networks:
            - carwashnetwork
        volumes:
            - "pgdata:/var/lib/postgresql/data"
            
    nginx:
        image: skava600/nginxconfigs
        restart: always
        networks:
            - carwashnetwork
        ports:
            - "5000:1222"

    carwash:
        environment:
            BOT_TOKEN: "1720752774:AAFiYNyLsAL3ecNxyFX4ZNmR88r6N7SJg5U"
            WEBHOOK_URL: "https://ff8df8d3d444.ngrok.io"
        image: skava600/carwash
        restart: always
        networks:
            - carwashnetwork
        depends_on:
            - carwashdb
volumes:
        pgdata:
